apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
      - name: fastapi
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
        ports:
        - containerPort: 80
